[package]
name = "evo"
version = "0.1.0"
edition = "2024"

[dependencies]
evo_common = { path = "../evo_common" }
clap = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
